### ISSUE TITLE
Hot Reload with reference to dll

### ISSUE THREAD

**Issue by vutle** [Urho-Net/Urho.Net#24]
Hi elix22,
Thanks for the .net Urho.

I would like to understand how hot reload works in relation to 3rd party library reference.
For example:   I have a component to be reloaded.   This component references C# project library or a dll.   
I add this library into the csproj file with

<Reference Include="PriorityQueues" >
        <HintPath>References\PriorityQueues.dll</HintPath>
    </Reference>

and inside DynamicComponentManager.cs  file with the two entries.

 private static Assembly priorityQueue = Assembly.Load(new AssemblyName("PriorityQueues"));

...
 MetadataReference.CreateFromFile(priorityQueue.Location),

I create my component with...    

Component comp = dynamicComponentManager.CreateComponent("Source/des.cs");

When I run debug through vs code I get the below error.   

Source/des.cs: : (0,0)-(0,0) CS8203: Invalid assembly name: Name contains invalid characters.

Is there any other setting that I need to be aware of?  
Thanks

**Comment by elix22** [comment]
Several steps 
Make sure the Assembly is copied to the bin folder , i.e. bin/Debug/netcoreapp3.1/PriorityQueues.dll

Might be that PriorityQueues.dll is dependent on additional assemblies that also have to be added to DynamicComponentManager.cs , but I guess you would see that in the error 

Upgrade to the latest Roslyn compiler , modify your  .csproj file 

> <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" />
  </ItemGroup>

**Comment by elix22** [comment]
Modify , remove "Source/"

> Component` comp = dynamicComponentManager.CreateComponent("des.cs");

**Comment by vutle** [comment]
Ok found the problem.  I need to also add Collection Assembly since the PriorityQueues dll referencing it. 
Also needs to add  Source to ApplicationOption.  

new ApplicationOptions(assetsFolder: "Data;CoreData;Source")

 The component is also assumed to have the same name as the file.

**Comment by vutle** [comment]
Thanks elix22..  All is great now.
