### ISSUE TITLE
configure on windows issue

### ISSUE THREAD

**Issue by vutle** [Urho-Net/Urho.Net#7]
![image](https://user-images.githubusercontent.com/6241928/120960962-37375500-c7a0-11eb-8026-bfeb0f8ee1cb.png)

running HelloWorld has the below error.  Looks like dll is not found.
G:\Urho.Net\NewBuild\Working Build\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(114,5): warning MSB3030: Could not copy the file "TEMPLATE_URHONET_HOME\template\libs\dotnet\urho\desktop\UrhoDotNet.dll" because it was not found.
G:\Urho.Net\NewBuild\Working Build\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(114,5): warning MSB4181: The "Copy" task returned false but did not log an error.
G:\Urho.Net\NewBuild\Working Build\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(118,5): warning MSB3030: Could not copy the file "TEMPLATE_URHONET_HOME\template\libs\dotnet\urho\desktop\UrhoDotNet.xml" because it was not found.
G:\Urho.Net\NewBuild\Working Build\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(118,5): warning MSB4181: The "Copy" task returned false but did not log an error.

**Comment by vutle** [comment]
I think the environment does not register correctly on Windows 10.
URHONET_HOME_ROOT and TEMPLATE_URHONET_HOME

This is what I currently do to get the HelloWord to work.

1) Comment out the below inside csproj
....
 
....
 
....

  

2) Manually copy Urho3d.dll, Core data and Data to bin folder.

----
PS:  The older version before clearing the issue section works perfectly.  This version has this bug in the last two iterations.

**Comment by elix22** [comment]
Thanks for reporting 
I tried and can't reproduce this issue on my Windows 10 machine 
I didn't touch this script for a very long time .
Can you please try and run it from the git-bash 
Probably you will find it in C:\Program Files\Git\git-bash.exe

```

Exmaple :
$ ./configure.sh

Urho.Net configured!

cat /c/Users/aloni/.urhonet_config/urhonethome
/e/Development/Urho.Net

cat /c/Users/aloni/.urhonet_config/UrhoNetHome.config
<UrhoNetHome>
  <add key="UrhoNetHome" value="E:/Development/Urho.Net" />
</UrhoNetHome>
```

**Comment by elix22** [comment]
OK I found the root cause .
You are using white spaces in your path "../**Working build**/Urho.Net" 
The script can't handle white spaces
Make sure that Urho.Net full path doesn't contain white spaces .
I will add some path checking into the script

**Comment by vutle** [comment]
Hi elix,  I tried remove the space, but it still shown an error.
I think the path does not register in the environment variable or vscode can't read the environment variable or something....

 URHONET_HOME_ROOT=TEMPLATE_URHONET_HOME
G:\Urho.Net\NewBuild\WorkingBuild\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(114,5): warning MSB3030: Could not copy the file "TEMPLATE_URHONET_HOME\template\libs\dotnet\urho\desktop\UrhoDotNet.dll" because it was not found.
G:\Urho.Net\NewBuild\WorkingBuild\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(114,5): warning MSB4181: The "Copy" task returned false but did not log an error.
G:\Urho.Net\NewBuild\WorkingBuild\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(118,5): warning MSB3030: Could not copy the file "TEMPLATE_URHONET_HOME\template\libs\dotnet\urho\desktop\UrhoDotNet.xml" because it was not found.
G:\Urho.Net\NewBuild\WorkingBuild\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(118,5): warning MSB4181: The "Copy" task returned false but did not log an error.
  HelloWorld -> G:\Urho.Net\NewBuild\WorkingBuild\Urho.Net\VuSample\HelloWorld\bin\Debug\netcoreapp3.1\Game.dll
G:\Urho.Net\NewBuild\WorkingBuild\Urho.Net\VuSample\HelloWorld\HelloWorld.csproj(126,5): error : Urho3D.dll not found are you sure URHONET_HOME_ROOT is pointing to the right place ?
The terminal process "C:\Program Files\dotnet\dotnet.exe 'build', 'G:\Urho.Net\NewBuild\WorkingBuild\Urho.Net\VuSample\HelloWorld/HelloWorld.csproj', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by elix22** [comment]
I have rewritten configure.bat entirely specifically for Windows , part of my main branch.
Please check it , it should work now.
If by any slight chance it doesn't please provide the output

**Comment by vutle** [comment]
Thanks new update fixed the issue.

**Comment by elix22** [comment]
OK , thanks
